// Generated by typings
// Source: node_modules/@angularclass/angular2-beta-to-rc-alias/src/beta-17/typings.d.ts
declare module "angular2/core" {
  export * from '@angular/core';
}

declare module "angular2/http" {
  export * from '@angular/http';
}

declare module 'angular2/platform/browser' {
  export * from '@angular/platform-browser'
}

declare module 'angular2/testing' {
  export * from '@angular/core/testing';
}

declare module 'angular2/router' {
  export * from '@angular/router';
}

declare module 'angular2/http/testing' {
  export * from '@angular/http/testing';
}
